name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Maven GitHub Packages credentials
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.ACTION_USER }}</username>
                <password>${{ secrets.ACTION_SECRET }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.ACTION_USER }}
          password: ${{ secrets.ACTION_SECRET }}

      - name: Debug secrets (TEMPORARY!)
        run: |
          echo "ACTION_USER=${{ secrets.ACTION_USER }}"
          echo "ACTION_SECRET=${{ secrets.ACTION_SECRET }}" | wc -c

      - name: Set up image name and tags
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          TIMESTAMP_TAG=$(date +%s)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "TIMESTAMP_TAG=$TIMESTAMP_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image with multiple tags
        run: |
          docker build -t ${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.vars.outputs.TIMESTAMP_TAG }} \
                       -t ${{ steps.vars.outputs.IMAGE_NAME }}:latest .

      - name: Push all tags to GitHub Container Registry
        run: |
          docker push ${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.vars.outputs.TIMESTAMP_TAG }}
          docker push ${{ steps.vars.outputs.IMAGE_NAME }}:latest
